### ISSUE TITLE
希望能提供内测机会啊

### ISSUE THREAD

**Issue by zealson** [Zzm317/V2Milk#1]
终于等来了高颜值GUI的V2RAY客户端了,有没有可能同时支持SS/SSR协议呢?总之期待提前参与测试呢

**Comment by zealson** [comment]
alpha还没发布么?大神

**Comment by Zzm317** [comment]
这项目本意是提供给V2RaySocks插件用的
之后可能会去掉登录单独做一个版本

**Comment by Zzm317** [comment]
请关注 github.com/zzm317/v2raym
这是单独的客户端

**Comment by zealson** [comment]
> 请关注 github.com/zzm317/v2raym
> 这是单独的客户端

那这个Milk是不是要买你家服务才能使用mac客户端啊?v2raym是针对普通Mac用户都能使用到的么?

**Comment by Zzm317** [comment]
> > 请关注 github.com/zzm317/v2raym
> > 这是单独的客户端
> 
> 那这个Milk是不是要买你家服务才能使用mac客户端啊?v2raym是针对普通Mac用户都能使用到的么?

v2milk是可以对接v2raysocks的客户端，v2raym是之后的普通用户都能使用的客户端
v2milk更多的是给购买了manager或者使用v2raysocks插件的机场主用来编译自己的客户端的

**Comment by zealson** [comment]
原来如此，这么说我就明白了，希望V2RayM当然UI能和V2Milk一样漂亮好用了，谢谢了🤗~那我就继续关注V2Raym的进度了，谢谢了，💪🏻加油，目前不管是Win还是Mac上的V2Ray不管是GUI还是体验都很差的!😅

**Comment by Zzm317** [comment]
ui一样的这个你放心 可理解为就是现在的v2milk去掉首页节点和登录什么的

**Comment by zealson** [comment]
那就太赞了👍🏻，希望到时能参与内测体验😆

**Comment by Zzm317** [comment]
实际上现在就在填自定义节点
然后win上的全局有bug我还在修
手头没win本还在折腾垃圾sb坑钱parallels desktop

**Comment by zealson** [comment]
可以去先来个macOS alpha 版呗~😄，我甘愿当小白鼠先，win下面有个V2ray的软件其实比mac版强大很多，就是太丑，Mac版目前那个v2ray 软件才是又丑又没什么功能…

**Comment by Zzm317** [comment]
目前的开发进程和编写进度顺序同步的 修链接的bug比自定义节点优先级高=-=
