### ISSUE TITLE
V2ray进程意外关闭

### ISSUE THREAD

**Issue by nescirem** [Zzm317/V2Milk#11]
系统环境、相关配置等与[Issue10](https://github.com/Zzm317/V2Milk/issues/10)相同。

现象：
无法正常调用V2ray内核
![界面截图](https://i.loli.net/2018/10/24/5bd08719cb376.png)
![内核所在文件夹](https://i.loli.net/2018/10/24/5bd08719d0b10.png)

V2ray内核版本：
尝试过3.47与3.34。

**Comment by Zzm317** [comment]
![jietu20181025-120420 2x](https://user-images.githubusercontent.com/8464161/47475489-300ce400-d84e-11e8-9bb1-ee680f95c1e1.jpg)
那么大三个MacOS,Linux,Windows文件夹被你吃了？
怎么readme都不好好看看清楚就来开这种无意义issue

**Comment by nescirem** [comment]
是鄙人粗心，让您废神了。
