### ISSUE TITLE
请问sysproxy.exe 与 proxy_conf_helper你在哪弄来的？求参考资料哟

### ISSUE THREAD

**Issue by yeluoqiuzhi** [Zzm317/V2Milk#12]
请问sysproxy.exe 与 proxy_conf_helper你在哪弄来的？求参考资料哟

**Comment by Zzm317** [comment]
https://github.com/erguotou520/electron-ssr/commit/647ac6c3055a7c68b66394283922d73011234ba9

**Comment by yeluoqiuzhi** [comment]
谢谢大佬

**Comment by RexkentZheng** [comment]
大佬，proxy_conf_helper文件还是没有找到，能说下这文件到底是做什么的么

**Comment by Zzm317** [comment]
自行仔细查阅
用于代理切换

**Comment by RexkentZheng** [comment]
> 自行仔细查阅
> 用于代理切换

大佬，仔细查阅后找到这个文件了，可是没太懂这个文件怎么来的。而且貌似这个文件只能修改socks代理，我想修改http和https代理的话只能使用networksetup指令，但是需要输入密码，有什么不用输入密码的方式么？大佬

**Comment by yeluoqiuzhi** [comment]
最完整最完美的跨平台的ss客户端定制，找我，我已经写一套完美的

**Comment by RexkentZheng** [comment]
> 最完整最完美的跨平台的ss客户端定制，找我，我已经写一套完美的

我没有想定制的意思，想自己写一个，关于proxy_conf_helper有什么建议么

**Comment by yeluoqiuzhi** [comment]
https://github.com/shadowsocks/ShadowsocksX-NG/blob/develop/proxy_conf_helper/main.m

这个就是proxy_conf_helper的源码，自己看呀

**Comment by Zzm317** [comment]
@yeluoqiuzhi 自己要找offer自己去开自己的项目去
在这个开源项目下面发这种定制找你几个意思？

**Comment by Zzm317** [comment]
> > 自行仔细查阅
> > 用于代理切换
> 
> 大佬，仔细查阅后找到这个文件了，可是没太懂这个文件怎么来的。而且貌似这个文件只能修改socks代理，我想修改http和https代理的话只能使用networksetup指令，但是需要输入密码，有什么不用输入密码的方式么？大佬

写成脚本放进bin目录最开始就让用户输入密码放进去然后直接execfile调用

**Comment by RexkentZheng** [comment]
谢到大佬，已经解决了
