### ISSUE TITLE
编译时出错

### ISSUE THREAD

**Issue by mayday12138** [Zzm317/V2Milk#2]
-bash-4.2# cat npm-debug.log
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/node/bin/node',
1 verbose cli   '/usr/local/node/bin/npm',
1 verbose cli   'run',
1 verbose cli   'packageWin' ]
2 info using npm@3.10.10
3 info using node@v6.10.2
4 verbose run-script [ 'prepackageWin', 'packageWin', 'postpackageWin' ]
5 info lifecycle V2Milk@0.0.4~prepackageWin: V2Milk@0.0.4
6 silly lifecycle V2Milk@0.0.4~prepackageWin: no script for prepackageWin, continuing
7 info lifecycle V2Milk@0.0.4~packageWin: V2Milk@0.0.4
8 verbose lifecycle V2Milk@0.0.4~packageWin: unsafe-perm in lifecycle true
9 verbose lifecycle V2Milk@0.0.4~packageWin: PATH: /usr/local/node/lib/node_modules/npm/bin/node-gyp-bin:/root/V2Milk/APP/node_modules/.bin:/usr/local/node/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/usr/local/go/bin:/usr/local/go/bin:/usr/local/go/bin:/usr/local/go/bin
10 verbose lifecycle V2Milk@0.0.4~packageWin: CWD: /root/V2Milk/APP
11 silly lifecycle V2Milk@0.0.4~packageWin: Args: [ '-c',
11 silly lifecycle   'electron-packager . V2Milk --platform=win32 --win32metadata.CompanyName=V2Milk --win32metadata.ProductName=V2Milk --out V2MilkAPP --arch=x64 --app-copyright=V2Milk.com --app-version=0.1.0 --electron-version=2.0.8 --overwrite --asar --ignore=extra/ --icon V2Milk.ico --extra-resource=extra/' ]
12 silly lifecycle V2Milk@0.0.4~packageWin: Returned: code: 1  signal: null
13 info lifecycle V2Milk@0.0.4~packageWin: Failed to exec packageWin script
14 verbose stack Error: V2Milk@0.0.4 packageWin: `electron-packager . V2Milk --platform=win32 --win32metadata.CompanyName=V2Milk --win32metadata.ProductName=V2Milk --out V2MilkAPP --arch=x64 --app-copyright=V2Milk.com --app-version=0.1.0 --electron-version=2.0.8 --overwrite --asar --ignore=extra/ --icon V2Milk.ico --extra-resource=extra/`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/usr/local/node/lib/node_modules/npm/lib/utils/lifecycle.js:255:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (/usr/local/node/lib/node_modules/npm/lib/utils/spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:886:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid V2Milk@0.0.4
16 verbose cwd /root/V2Milk/APP
17 error Linux 3.10.0-862.3.2.el7.x86_64
18 error argv "/usr/local/node/bin/node" "/usr/local/node/bin/npm" "run" "packageWin"
19 error node v6.10.2
20 error npm  v3.10.10
21 error code ELIFECYCLE
22 error V2Milk@0.0.4 packageWin: `electron-packager . V2Milk --platform=win32 --win32metadata.CompanyName=V2Milk --win32metadata.ProductName=V2Milk --out V2MilkAPP --arch=x64 --app-copyright=V2Milk.com --app-version=0.1.0 --electron-version=2.0.8 --overwrite --asar --ignore=extra/ --icon V2Milk.ico --extra-resource=extra/`
22 error Exit status 1
23 error Failed at the V2Milk@0.0.4 packageWin script 'electron-packager . V2Milk --platform=win32 --win32metadata.CompanyName=V2Milk --win32metadata.ProductName=V2Milk --out V2MilkAPP --arch=x64 --app-copyright=V2Milk.com --app-version=0.1.0 --electron-version=2.0.8 --overwrite --asar --ignore=extra/ --icon V2Milk.ico --extra-resource=extra/'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the V2Milk package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     electron-packager . V2Milk --platform=win32 --win32metadata.CompanyName=V2Milk --win32metadata.ProductName=V2Milk --out V2MilkAPP --arch=x64 --app-copyright=V2Milk.com --app-version=0.1.0 --electron-version=2.0.8 --overwrite --asar --ignore=extra/ --icon V2Milk.ico --extra-resource=extra/
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs V2Milk
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls V2Milk
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]
-bash-4.2#

**Comment by Zzm317** [comment]
2 info using npm@3.10.10
3 info using node@v6.10.2
你是上世纪的远古用户么
