### ISSUE TITLE
希望大佬透露下nodejs和npm版本

### ISSUE THREAD

**Issue by mayday12138** [Zzm317/V2Milk#4]
编译了好多次都报错，试过很多的版本了

**Comment by Zzm317** [comment]
NagakaSuzume:~ zzm317$ npm -v
6.4.1
NagakaSuzume:~ zzm317$ electron -v
v2.0.8
NagakaSuzume:~ zzm317$ node -v
v10.11.0

**Comment by Zzm317** [comment]
你就全部最新的就好 如果编译还是有问题并且不是node版本问题再来提issue就ok
