### ISSUE TITLE
最新版我还是出错了

### ISSUE THREAD

**Issue by mayday12138** [Zzm317/V2Milk#5]

**Comment by Zzm317** [comment]
你自己环境变量问题或者electron安装有问题
Failed to locate module "electron" from "."
检查electron是否安装正常node和npm路径是否正确
不是程序的问题别找我
我开源的是程序不是新手入门教学
这种无意义issue别开了

**Comment by mayday12138** [comment]
弄了好久终于成功了，总结一下，以免其他人走歪路吧，最好npm install -g cnpm ，然后用cnpm安装electron，最后用cnpm打包，用npm有时碰到奇怪的问题，还有就是非windows平台编译Windows应用是要先安装wine
