### ISSUE TITLE
请教

### ISSUE THREAD

**Issue by luckypoem** [Zzm317/V2Milk#7]
"将最新的 V2Ray-Core 放入 APP/extra/v2ray-core 的对应目录下 "是指把v2ray-core-3.46.tar.gz解压到
 APP/extra/v2ray-core/目录下吗

**Comment by Zzm317** [comment]
请不要在没仔细阅读readme的情况下发这种无用issue
https://raw.githubusercontent.com/Zzm317/V2Milk/master/images/6.jpg
