### ISSUE TITLE
v2ray状态反馈

### ISSUE THREAD

**Issue by mayday12138** [Zzm317/V2Milk#8]
已经更新配置文件啦w
正在加载 GLOBAL 模式～
配置文件写入成功～
V2Ray进程启动中。。。
正在加载 GLOBAL 模式～
配置文件写入成功～
V2Ray进程的进程退出码是 null ~
V2Ray进程启动中。。。
其实是已经启动成功了

**Comment by mayday12138** [comment]
v2ray core用的最新版

**Comment by Zzm317** [comment]
3.46问题

**Comment by Zzm317** [comment]
fixed 
https://github.com/Zzm317/V2Milk/commit/7f4e24a69df3d2cf0bfcd9b05c1b3fd603b74a2f
