### ISSUE TITLE
deepin下无法正常使用

### ISSUE THREAD

**Issue by 500646** [Zzm317/V2Milk#9]
启动中。。。
启动完成～
载入配置文件～
载入语言：zh-CN
PAC端口：7777
Socks5端口：1081
HTTP端口：8001
PAC已经载入啦～
已载入自定义节点配置文件～
自定义节点 0 个
订阅 0 个
Gtk-Message: 00:07:51.504: GtkDialog mapped without a transient parent. This is discouraged.

无法添加自定义节点. 表现为点了保存没有反应..
可以使用订阅链接添加节点. 但是点击全局连接按钮。程序出错。PAC连接也是一样的错误.
![20181014001013](https://user-images.githubusercontent.com/10594524/46907480-a99afd00-cf45-11e8-965a-eb52ca26e262.png)

**Comment by Zzm317** [comment]
自定义节点什么时候说过写好了 你自己看看编写进度
linux要自己把启动那行注释先去掉再开
https://github.com/Zzm317/V2Milk/blob/master/APP/src/main/main.js#L768

**Comment by Zzm317** [comment]
我估计你是没去掉
stdout是要你先cps运行了才会有的 因为我没测试linux所以我把那行的启动注释掉了
这就导致v2rayserver是个null，null自然不存在.stdout也就是上面的undefined的error

**Comment by Zzm317** [comment]
如果你去掉以后测试通过了麻烦回复一下本issue
我就去掉注释直接推然后标记linux测试通过了
手头没linux环境主要是

**Comment by 500646** [comment]
抱歉没细看readme.去掉注释后,按照extra/v2ray-core/Linux/v2ray这个路径弄好后,报错如下:

![20181014011727](https://user-images.githubusercontent.com/10594524/46908042-ef0ff800-cf4e-11e8-9b54-13beda35cbae.png)

**Comment by Zzm317** [comment]
啊对了 还有 
linux的权限机制我不太清楚 
你估计得给程序权限让他把配置文件写入了
或者把他存config.json的文件目录给权限
